### ISSUE TITLE
Dependency erros

### ISSUE THREAD

**Issue by mbaquir** [imazen/folioxml#11]
Hi!
Thanks for sharing this library. I cloned the repository on NetBeans and now Im having issues with dependencies. The error I get when I try to run it is:
Failed to execute goal on project folioxml-commandline: Could not resolve dependencies for project folioxml:folioxml-commandline:jar:0.0.1-SNAPSHOT: Could not find artifact folioxml:folioxml-lucene:jar:0.0.1-SNAPSHOT -> [Help 1]

Any idea on how to fix this problem?

Thanks

**Comment by nathanaeljones** [comment]
You need to switch to the develop branch and run maven. 

https://github.com/imazen/folioxml/tree/develop#running-the-command-line-app


I would also suggest IntelliJ over Netbeans, but you don't need either to build/run this app.

**Comment by DonnyLi** [comment]
Hey Mr.Jones,

When running the command line app using these commands:

* mvn clean compile assembly:single -U -B -fae
* java -jar commandline/target/folioxml-commandline-jar-with-dependencies.jar -config core/folioxml/resources/test.yaml -export folio_help

I receive a file not found exception error where it's looking for FolioHlp.FFF. I'm not sure if this is a test case or you were originally testing your app on this file. How can I remedy this problem or what commands would I have to use to convert a file in a specific folder. Furthermore, where would the converted file be?

**Comment by nathanaeljones** [comment]
This issue is related to: https://github.com/imazen/folioxml/issues/9

If we can find/create a public domain test infobase we can replaces FolioHlp.FFF. Given that different versions of the JVM can have different regex behaviors, these tests are important.

**Comment by DonnyLi** [comment]
If I needed to conduct my own test on my own .FFF file (say it's named test.FFF) what would my steps be?

**Comment by nathanaeljones** [comment]
I would need to help set this up. Would you be able to collaborate me on  #9 ?  I'm using Folio Views 4.7.1. Created repo here: https://github.com/imazen/folio-test-infobases

**Comment by DonnyLi** [comment]
As much as I would love to collaborate with you on the issue, I am in the same boat as you are. I do not own the rights to distribute the file and cannot push it into your repo. Is there a way for me to set it up so that I could test on my own accord?

**Comment by nathanaeljones** [comment]
I'm afraid not, unless you have a licensed copy of the Folio Help Manual. My suggestion was that we create new public domain content in a new infobase to exercise all of the features.

**Comment by DonnyLi** [comment]
I actually do have a licensed copy of the Folio Help Manual. I have a .fff file that I need to convert into either xhtml or xml. How can I use your tool to allow me to do this?

**Comment by nathanaeljones** [comment]
If you export the manual to FFF, then you can place those files in the /files/folio-help directory (within the project), and it should build & test. I suggest the develop branch.

**Comment by DonnyLi** [comment]
I tried using your tool on my FolioHlp.FFF file and was able to get a folder with a few .txt, .css, .html files where the html file contained readable content displayed in a fairly aesthetically pleasing manner. However, while the tool was running it ran into an error that gave an exception in the main thread:
*    at folioxml.export.html.LinkMapper.process(LinkMapper.java:45)
*    at folioxml.export.html.MultiRunner.process(MultiRunner.java:36)
*    at folioxml.export.plugins.ApplyProcessor.onRecordComplete(ApplyProcessor.java:61)
*    at folioxml.export.InfobaseSetVisitor.complete(InfobaseSetVisitor.java:127)
*    at folioxml.export.ExportRunner.Export(ExportRunner.java:113)
*    at folioxml.command.Main.run(Main.java:70)
*    at folioxml.command.Main.main(Main.java:40)

Also, would it be possible to use this tool on a file other than the FolioHlp file given that I already have my own help manual?

**Comment by nathanaeljones** [comment]
LinkMapper is a new feature I just added yesterday; it may be a bit buggy. You could roll back a commit or comment it out.
