### ISSUE TITLE
SLX not does not output file in Maven test.

### ISSUE THREAD

**Issue by BillTheGoat** [imazen/folioxml#8]
Fails to compile with test error in TEST-folioxml.slx.SlxTransformerTest.xml:

error message="C:\...\folioxml-master\files\folio-help\export\Translation.slx (The system cannot find the path specified)" type="java.io.FileNotFoundException"![CDATA[java.io.FileNotFoundException: C:\...\folioxml-master\files\folio-help\export\Translation.slx (The system cannot find the path specified)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at folioxml.slx.SlxTransformerTest.XmlExport(SlxTransformerTest.java:29)
	at folioxml.slx.SlxTransformerTest.FolioHelp(SlxTransformerTest.java:21)
]]
/error

**Comment by nathanaeljones** [comment]
Our maven test depends upon a test file that we don't have rights to distribute. It's very common though - the Folio Help File. 

See https://github.com/imazen/folioxml/blob/master/.travis.yml#L10

If you ensure this is downloaded and present, you can run the tests. We can't distribute it, unfortunately, but you can find it in your copy of Folio. 

I would love to have a public domain test infobase that comprehensively exercises the 120+ tags as well as the help infobase does.

**Comment by BillTheGoat** [comment]
I get this error using the folio help file from folio builder 4.6. We managed to get it working by building without tests.
